version: '3.11'

services:
  ollama:
    image: ollama/ollama:latest
    container_name: ollama_container
    networks:
      - mynetwork

  nginx:
    image: nginx:latest
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
    ports:
      - 11434:11434
    depends_on:
      - ollama
    networks:
      - mynetwork

  # mybot:
  #   build:
  #     context: /home/runner/work/simplon_brief09_chatbot_integration/simplon_brief09_chatbot_integration/my_bot/
  #   image: kevb09registry.azurecr.io/my_bot
  #   container_name: mybot_container
  #   ports:
  #     - "8000:8000"
  #   depends_on:
  #     - ollama
  #   networks:
  #     - mynetwork

  mysite:
    build:
      context: /home/runner/work/simplon_brief09_chatbot_integration/simplon_brief09_chatbot_integration/my_site/
    image: kevb09registry.azurecr.io/my_site
    container_name: mysite_container
    ports:
      - "5000:5000"
    depends_on:
      - nginx
    networks:
      - mynetwork

networks:
  mynetwork: