name: Azure Deployment

on:
  push:
    branches:
      - ollama-chatbot

permissions:
  id-token: write
  contents: read

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
      
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Log in with Azure
        uses: azure/login@v1
        with:
          creds: '${{ secrets.AZURE_CREDENTIALS }}'

      - name: Azure CLI script
        uses: azure/CLI@v1
        with:
          azcliversion: latest
          inlineScript: |
            az account show

      - name: Login to Azure Container Registry
        uses: azure/docker-login@v1
        with:
          login-server: kevb09registry.azurecr.io
          username: kevb09registry
          password: ${{ secrets.ACR_PASSWORD }}

      - name: Build Docker images using Docker Compose
        run: |
          docker-compose up --build -d
          docker tag ollama/ollama:latest kevb09registry.azurecr.io/ollama
          docker push kevb09registry.azurecr.io/my_site
          docker push kevb09registry.azurecr.io/my_bot
          docker push kevb09registry.azurecr.io/ollama
        
      - name: Find and Replace
        uses: jacobtomlinson/gha-find-replace@v2
        with:
          find: "password.registry"
          replace: ${{ secrets.ACR_PASSWORD }}
          regex: false
          include: 'deploy-aci.yaml'
          
      - name: Delete Previous Same Container Instances
        run: az container delete --resource-group kev_b16 --name kevChatbotGroupB09 --yes
    
      - name: Deploy to Azure Container Instances
        run: az container create --resource-group kev_b16 --file deploy-aci.yaml

      - name: Pull model on Ollama container
        run: az container exec --resource-group kev_b16 --name kevChatbotGroupB09 --container-name ollama --exec-command "ollama pull phi3"